title: Mario A. Sandoval-Molina
email: mas798@cornell.edu
description: >- # this means to ignore newlines until "baseurl:"
  PhD Candidate in Ecology and Evolutionary Biology at Cornell University.
  Researching insect-plant interactions and chemical ecology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mariosandovalmx
github_username: mariosandovalmx

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Custom settings
google_analytics: G-TKKFWCWBDY

# Navigation
header_pages:
  - index.md
  - research.md
  - publications.md
  - cv.md
  - contact.md
